# Generated by Django 5.1.7 on 2025-04-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='nombre_producto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
