# Generated by Django 5.1.7 on 2025-04-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_ubicacion_alter_producto_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
